drop view flights_view;
CREATE VIEW flights_view AS
SELECT
  CAST("YEAR" AS INTEGER) AS "YEAR",
  CAST("MONTH" AS INTEGER) AS "MONTH",
  CAST("DAY" AS INTEGER) AS "DAY",
  CAST(DAY_OF_WEEK AS INTEGER) AS DAY_OF_WEEK,
  AIRLINE,
  CAST(FLIGHT_NUMBER AS INTEGER) AS FLIGHT_NUMBER,
  TAIL_NUMBER,
  ORIGIN_AIRPORT,
  DESTINATION_AIRPORT,
  case
	when SCHEDULED_DEPARTURE = '2400' then TO_TIMESTAMP("YEAR" || '-' || LPAD("MONTH", 2, '0') || '-' || LPAD("DAY", 2, '0') || ' ' || LPAD('0000', 4, '0'), 'YYYY-MM-DD HH24MI')
	else TO_TIMESTAMP("YEAR" || '-' || LPAD("MONTH", 2, '0') || '-' || LPAD("DAY", 2, '0') || ' ' || LPAD(SCHEDULED_DEPARTURE, 4, '0'), 'YYYY-MM-DD HH24MI')
  end AS SCHEDULED_DEPARTURE,
  case
	when DEPARTURE_TIME = '2400' then TO_TIMESTAMP("YEAR" || '-' || LPAD("MONTH", 2, '0') || '-' || LPAD("DAY", 2, '0') || ' ' || LPAD('0000', 4, '0'), 'YYYY-MM-DD HH24MI')
	else TO_TIMESTAMP("YEAR" || '-' || LPAD("MONTH", 2, '0') || '-' || LPAD("DAY", 2, '0') || ' ' || LPAD(DEPARTURE_TIME, 4, '0'), 'YYYY-MM-DD HH24MI')
  end AS DEPARTURE_TIME,
  CAST(DEPARTURE_DELAY AS INTEGER) AS DEPARTURE_DELAY,
  CAST(TAXI_OUT AS INTEGER) AS TAXI_OUT,
  case
	when WHEELS_OFF = '2400' then TO_TIMESTAMP("YEAR" || '-' || LPAD("MONTH", 2, '0') || '-' || LPAD("DAY", 2, '0') || ' ' || LPAD('0000', 4, '0'), 'YYYY-MM-DD HH24MI')
	else TO_TIMESTAMP("YEAR" || '-' || LPAD("MONTH", 2, '0') || '-' || LPAD("DAY", 2, '0') || ' ' || LPAD(WHEELS_OFF, 4, '0'), 'YYYY-MM-DD HH24MI')
  end AS WHEELS_OFF,
  CAST(SCHEDULED_TIME AS INTEGER) AS SCHEDULED_TIME,
  CAST(ELAPSED_TIME AS INTEGER) AS ELAPSED_TIME,
  CAST(AIR_TIME AS INTEGER) AS AIR_TIME,
  CAST(DISTANCE AS INTEGER) AS DISTANCE,
  case
	when WHEELS_ON = '2400' then TO_TIMESTAMP("YEAR" || '-' || LPAD("MONTH", 2, '0') || '-' || LPAD("DAY", 2, '0') || ' ' || LPAD('0000', 4, '0'), 'YYYY-MM-DD HH24MI')
	else TO_TIMESTAMP("YEAR" || '-' || LPAD("MONTH", 2, '0') || '-' || LPAD("DAY", 2, '0') || ' ' || LPAD(WHEELS_ON, 4, '0'), 'YYYY-MM-DD HH24MI')
  end AS WHEELS_ON,
  CAST(TAXI_IN AS INTEGER) AS TAXI_IN,
  case
	when SCHEDULED_ARRIVAL = '2400' then TO_TIMESTAMP("YEAR" || '-' || LPAD("MONTH", 2, '0') || '-' || LPAD("DAY", 2, '0') || ' ' || LPAD('0000', 4, '0'), 'YYYY-MM-DD HH24MI')
	else TO_TIMESTAMP("YEAR" || '-' || LPAD("MONTH", 2, '0') || '-' || LPAD("DAY", 2, '0') || ' ' || LPAD(SCHEDULED_ARRIVAL, 4, '0'), 'YYYY-MM-DD HH24MI')
  end AS SCHEDULED_ARRIVAL,
  case
	when ARRIVAL_TIME = '2400' then TO_TIMESTAMP("YEAR" || '-' || LPAD("MONTH", 2, '0') || '-' || LPAD("DAY", 2, '0') || ' ' || LPAD('0000', 4, '0'), 'YYYY-MM-DD HH24MI')
	else TO_TIMESTAMP("YEAR" || '-' || LPAD("MONTH", 2, '0') || '-' || LPAD("DAY", 2, '0') || ' ' || LPAD(ARRIVAL_TIME, 4, '0'), 'YYYY-MM-DD HH24MI')
  end AS ARRIVAL_TIME,
  CAST(ARRIVAL_DELAY AS INTEGER) AS ARRIVAL_DELAY,
  CAST(DIVERTED AS BOOLEAN) AS DIVERTED,
  CAST(CANCELLED AS BOOLEAN) AS CANCELLED,
  CANCELLATION_REASON
-- CAST(AIR_SYSTEM_DELAY AS INTEGER) AS AIR_SYSTEM_DELAY
-- CAST(SECURITY_DELAY AS INTEGER) AS SECURITY_DELAY,
-- CAST(AIRLINE_DELAY AS INTEGER) AS AIRLINE_DELAY,
-- CAST(LATE_AIRCRAFT_DELAY AS INTEGER) AS LATE_AIRCRAFT_DELAY,
-- CAST(WEATHER_DELAY AS INTEGER) AS WEATHER_DELAY
FROM flights f
WHERE EXISTS (SELECT 1 FROM airports a WHERE f.origin_airport = a.iata_code)
  AND EXISTS (SELECT 1 FROM airports a2 WHERE f.destination_airport = a2.iata_code)
  AND f.cancelled = '0'
  AND f.diverted = '0'